import { defineType, defineField, defineArrayMember } from 'sanity'
import { RocketIcon } from '@sanity/icons'

export const service = defineType({
  name: 'service',
  title: 'Service',
  type: 'document',
  icon: RocketIcon,
  fields: [
    defineField({
      name: 'title',
      title: 'Title',
      type: 'string',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'slug',
      title: 'Slug (URL ID)',
      type: 'slug',
      description: 'Used as the section ID (e.g. "system-engineering")',
      options: { source: 'title', maxLength: 96 },
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'subtitle',
      title: 'Subtitle / Badge Text',
      type: 'string',
      description: 'Short label shown in the badge (e.g. "Infrastructure Excellence")',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'description',
      title: 'Short Description',
      type: 'text',
      rows: 3,
      description: 'Brief description for the sidebar overview',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'heroDescription',
      title: 'Hero Description',
      type: 'text',
      rows: 4,
      description: 'Longer description shown in the hero/header area of each service section',
    }),
    defineField({
      name: 'icon',
      title: 'Icon',
      type: 'string',
      description: 'Lucide icon name for the service',
      options: {
        list: [
          { title: 'Server', value: 'Server' },
          { title: 'Code', value: 'Code2' },
          { title: 'Cloud', value: 'Cloud' },
          { title: 'Headphones', value: 'Headphones' },
          { title: 'Graduation Cap', value: 'GraduationCap' },
          { title: 'Database', value: 'Database' },
          { title: 'Shield', value: 'Shield' },
          { title: 'Monitor', value: 'Monitor' },
          { title: 'Network', value: 'Network' },
          { title: 'Settings', value: 'Settings' },
          { title: 'Smartphone', value: 'Smartphone' },
          { title: 'Globe', value: 'Globe' },
          { title: 'Layers', value: 'Layers' },
          { title: 'Wrench', value: 'Wrench' },
          { title: 'Activity', value: 'Activity' },
          { title: 'Target', value: 'Target' },
          { title: 'Lightbulb', value: 'Lightbulb' },
          { title: 'HardDrive', value: 'HardDrive' },
          { title: 'Cpu', value: 'Cpu' },
          { title: 'Lock', value: 'Lock' },
          { title: 'TrendingUp', value: 'TrendingUp' },
          { title: 'BookOpen', value: 'BookOpen' },
          { title: 'TestTube', value: 'TestTube' },
          { title: 'FileCheck', value: 'FileCheck' },
          { title: 'Presentation', value: 'Presentation' },
        ],
      },
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'ctaPrimaryText',
      title: 'Primary Button Text',
      type: 'string',
      description: 'Text for the main call-to-action button (e.g. "Schedule Assessment")',
    }),
    defineField({
      name: 'ctaSecondaryText',
      title: 'Secondary Button Text',
      type: 'string',
      description: 'Text for the secondary button (e.g. "View Case Studies")',
    }),
    defineField({
      name: 'features',
      title: 'Features',
      type: 'array',
      of: [
        defineArrayMember({
          type: 'object',
          name: 'feature',
          title: 'Feature',
          fields: [
            defineField({
              name: 'title',
              title: 'Title',
              type: 'string',
              validation: (Rule) => Rule.required(),
            }),
            defineField({
              name: 'description',
              title: 'Description',
              type: 'text',
              rows: 2,
              validation: (Rule) => Rule.required(),
            }),
            defineField({
              name: 'icon',
              title: 'Icon',
              type: 'string',
              options: {
                list: [
                  { title: 'Network', value: 'Network' },
                  { title: 'Database', value: 'Database' },
                  { title: 'Shield', value: 'Shield' },
                  { title: 'HardDrive', value: 'HardDrive' },
                  { title: 'Monitor', value: 'Monitor' },
                  { title: 'Smartphone', value: 'Smartphone' },
                  { title: 'Settings', value: 'Settings' },
                  { title: 'TestTube', value: 'TestTube' },
                  { title: 'Cloud', value: 'Cloud' },
                  { title: 'Layers', value: 'Layers' },
                  { title: 'Server', value: 'Server' },
                  { title: 'Wrench', value: 'Wrench' },
                  { title: 'Activity', value: 'Activity' },
                  { title: 'Headphones', value: 'Headphones' },
                  { title: 'Target', value: 'Target' },
                  { title: 'GraduationCap', value: 'GraduationCap' },
                  { title: 'TrendingUp', value: 'TrendingUp' },
                  { title: 'BookOpen', value: 'BookOpen' },
                  { title: 'Cpu', value: 'Cpu' },
                  { title: 'Globe', value: 'Globe' },
                  { title: 'Lightbulb', value: 'Lightbulb' },
                  { title: 'FileCheck', value: 'FileCheck' },
                ],
              },
            }),
            defineField({
              name: 'capabilities',
              title: 'Capabilities',
              type: 'array',
              of: [{ type: 'string' }],
              description: 'List of capability bullet points (used in System Engineering style)',
            }),
            defineField({
              name: 'techTags',
              title: 'Tech Tags',
              type: 'array',
              of: [{ type: 'string' }],
              description: 'Technology tags (used in Software Development style)',
            }),
            defineField({
              name: 'stat',
              title: 'Stat Badge',
              type: 'string',
              description: 'Short stat text (used in Cloud Solutions style, e.g. "100% Data Sovereignty")',
            }),
            defineField({
              name: 'tag',
              title: 'Tag',
              type: 'string',
              description: 'Category tag (used in Consultancy style, e.g. "Strategic")',
            }),
          ],
          preview: {
            select: { title: 'title', subtitle: 'description' },
          },
        }),
      ],
    }),
    defineField({
      name: 'stats',
      title: 'Statistics',
      type: 'array',
      description: 'Key metrics displayed in the stats bar',
      of: [
        defineArrayMember({
          type: 'object',
          name: 'stat',
          title: 'Statistic',
          fields: [
            defineField({
              name: 'label',
              title: 'Label',
              type: 'string',
              validation: (Rule) => Rule.required(),
            }),
            defineField({
              name: 'value',
              title: 'Value',
              type: 'number',
              validation: (Rule) => Rule.required(),
            }),
            defineField({
              name: 'prefix',
              title: 'Prefix',
              type: 'string',
              description: 'Text before the number (e.g. "< " or "Tier ")',
            }),
            defineField({
              name: 'suffix',
              title: 'Suffix',
              type: 'string',
              description: 'Text after the number (e.g. "%" or "/7/365")',
            }),
            defineField({
              name: 'isFloat',
              title: 'Is Decimal?',
              type: 'boolean',
              initialValue: false,
            }),
          ],
          preview: {
            select: { title: 'label', subtitle: 'value' },
          },
        }),
      ],
    }),
    defineField({
      name: 'order',
      title: 'Display Order',
      type: 'number',
      description: 'Lower numbers appear first',
    }),
  ],
  orderings: [
    {
      title: 'Display Order',
      name: 'orderAsc',
      by: [{ field: 'order', direction: 'asc' }],
    },
  ],
  preview: {
    select: {
      title: 'title',
      subtitle: 'subtitle',
    },
  },
})

